MODEL:
  NAME: 'ResNet50'
DATASET:
  LABEL_SIZE: 1
  IMAGE_SIZE: 32
  NUM_CHANNELS: 3
  PIXEL_DEPTH: 255
  NUM_CLASSES: 10
  LOAD_NUM: 10000
  TRAIN_NUMS: 50000
  TEST_NUM: 10000
TRAIN:
  BATCH_SIZE: 100
  MAX_EPOCH: 30